### ISSUE TITLE
node.fixed

### ISSUE THREAD

**Issue by daralthus** [samizdatco/arbor#3]
Hi, it looks like node.fixed has no effect on the physics. 
You can try the sample project. 
It only seems to work for the dragging, but it is because the "dragged" function sets some new coordinates when the mouse is moving.
If you add a node with the fixed property, then it has no effects and will still move.
Also adding a node with some default starting points, doesn't seems to work also.

Thx for any ideas!

**Comment by MPV** [comment]
Agreed, I have found the same to be true. 

It would be useful i.e. when you want a specific node to be locked in the middle and have its edges+nodes floating around it.

**Comment by srobertson** [comment]
Same here, fixed appears to have no effect when initially using addNode

**Comment by samizdatco** [comment]
Fixed.

**Comment by gruppler** [comment]
Is this really fixed? In the included sample project, it doesn't appear to be.

Try dragging a node. If you continue to hold the mouse button down but don't move the mouse, according to the code, the node should be fixed, yet it continues to move.

**Comment by brucethomax** [comment]
I am having a hard time with this as well.  Nothing I do fixes the node...

**Comment by wirthchris** [comment]
I had the same issue and looked at the Neo4J-Browser sources, because they managed to fix a dragged node. 
Adding this line to the particleSystem initialization seems to do the trick: @particleSystem.screenStep(0.000). With this line in place a node stays where it is when I set fixed=true. 
However, the boundaries of the canvas seem to have no effect anymore, I now have nodes moving out of sight all the time :( Any ideas???
